### ISSUE TITLE
Add generic support for the HTTP Link Header

### ISSUE THREAD

**Issue by jdesrosiers** [jdesrosiers/api-browser-web#12]
Read `Link` headers from response headers and display links that can be followed. Links should be clickable. That means it should make a new request, update the UrlBar url, and update the hash location.

https://tools.ietf.org/html/rfc8288

Acceptance Criteria:
```
Given a response
 When the response contains Link headers
 Then those links should be displayed
  And the user should be able to click them.

Given a response with Link headers
 When the user clicks on a link
 Then a request should be made to that URL
  And the response returned should be displayed
  And the URL in the UrlBar should be updated
  And the hash in the host bar should be updated.
```

**Comment by jdesrosiers** [comment]
I just pushed up a dummy Link that you can use.

**Comment by jdesrosiers** [comment]
I'd like it to look something like this

![screenshot from 2018-04-06 20-35-56](https://user-images.githubusercontent.com/716571/38507890-9ed50674-3bd2-11e8-93d3-001405cbf42a.png)

**Comment by jdesrosiers** [comment]
Last time I looked, I wasn't never able to find a library for parsing link headers. For now it's good enough to assume that Links will rigidly conform to the pattern `<href>; rel="rel"; title="Title"`. A simple regular expression is sufficient. I have a half finished parser lying around that I can replace it with later.

**Comment by bean00** [comment]
@jdesrosiers Just to confirm, regarding the functionality, the user should click on `Title` to activate the link, right? And the `rel` just shows what the relation is. So, for `</foo>; rel="foo"; title="foo"`, it should look like this:

![screen shot 2018-04-11 at 9 39 53 am](https://user-images.githubusercontent.com/13635808/38630622-506ebcbe-3d6c-11e8-8fd7-06767085f26a.png)

*Also, I'm not going to focus too much on the styling right now

**Comment by jdesrosiers** [comment]
@bean00 Yes, that's all correct.
