### ISSUE TITLE
UrlBar validation

### ISSUE THREAD

**Issue by jdesrosiers** [jdesrosiers/api-browser-web#8]
Use JsonSchema validation to ensure the value of the UrlBar is a URL. Don't attempt to request a URL if the UrlBar does not contain a URL. Validator should be `ajv` using `draft-06`.

Acceptance Criteria:
```
Given that the user enters a value in the UrlBar
  And the value is a valid URL
 When the user presses "Enter"
 Then a request is made.

Given that the user enters a value in the UrlBar
  And the value is not a valid URL
 When the user presses "Enter"
 Then the border around the API UrlBar turns red
  And no request is made
  And no output is displayed.

Given that the user enters a value in the UrlBar
  And the value is not a valid URL
  And the user presses "Enter"
 When the URL is modified to a valid URL
  And the user presses "Enter"
 Then the border color resets to normal
  And a request is made.
```

**Comment by bean00** [comment]
@jdesrosiers, so, acceptance criteria like the following?
```
Given that the user enters a value in the UrlBar
 When the value is a valid URL
 Then a request is made.

Given that the user enters a value in the UrlBar
 When the value is not a valid URL
 Then no request is made
  And no output is displayed.
```

**Comment by jdesrosiers** [comment]
@bean00 Looks good, but we also need to add some feedback that there was an error. Let's start with changing the input's border to red. If we need to do more than that, we can add that in the future. When the url is modified, the border color should reset back to normal.

Also, please update the issue's description with your Given/When/Then once you add the feedback stuff.

**Comment by bean00** [comment]
@jdesrosiers I've updated the acceptance criteria. Please let me know what other comments you have. Thanks!
